Test #27
dequelabs/ngA11y pull request #28
Opened 2017-02-02 22:39 UTC by marcysutton

I couldn't get the code to work at all when writing a test for #27, so I modified it. The inputs were never found before...I'm not sure how that ever worked. This also modifies the code in #27–we don't have to pass in the form name on submit because the directive already has access to it.

cc @iandotkelly @dylanb

2017-02-03 03:37 UTC, dylanb requested changes

2017-02-03 03:37 UTC, dylanb commented on Gruntfile.js
> +                    '* Copyright (C) 2017 Deque Systems Inc., All Rights Reserved',
should be 2015 - 2017

2017-02-03 03:37 UTC, dylanb commented on dist/nga11yfocus.min.js
> +* Copyright (C) 2017 Deque Systems Inc., All Rights Reserved
same here

2017-02-03 18:51 UTC, marcysutton commented on Gruntfile.js
> +                    '* Copyright (C) 2017 Deque Systems Inc., All Rights Reserved',
Done

2017-02-04 00:56 UTC, chandramuralis commented
Looks fine to me. My only concern is now we have a separate scope, if that's ok with the design I'm fine with it.

2017-02-06 13:35 UTC, dylanb approved these changes

2017-02-06 13:36 UTC, merged

2017-02-07 20:53 UTC, chandramuralis commented
Is this released yet?

2017-02-09 17:21 UTC, marcysutton commented
It is now! I was able to preserve your commits in this PR, so they are recognized in the code history. Thanks for your contributions! https://www.npmjs.com/package/ng-a11y